# Generated by Django 2.2.7 on 2021-04-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_information_app', '0005_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationstaffs',
            old_name='stafff_id',
            new_name='staff_id',
        ),
    ]
